### ISSUE TITLE
export all structs and funcs

### ISSUE THREAD

**Issue by kevin-shelaga** [Fallenstedt/twitter-stream#23]
example of an un-exported struct `*twitterstream.twitterApi`

**Comment by Fallenstedt** [comment]
[I can adjust some exports](https://github.com/Fallenstedt/twitter-stream/pull/28/files), but I don't think exporting every function is the right approach. Was there certain utilities in the library you needed? Did you encounter trouble mocking part of this library?

**Comment by kevin-shelaga** [comment]
Ya, exporting all isnt a goo idea. I suppose a minimum just the major components so that they can be passed in as param for various functions

**Comment by Fallenstedt** [comment]
I've promoted some structs to be exported, and I also updated how some interfaces are used. This will be available in 0.3.3
